### ISSUE TITLE
Craft 5.x update

### ISSUE THREAD

**Issue by hotovec** [TopShelfCraft/SuperSort#17]
Hello, do you have plan support Craft 5? 
Now its not possible to install your plugin. 
Thanks.
MH.

**Comment by TUSAB-web** [comment]
I’d like to ask the same question. If it’s not going to be updated, please let me know so I can re-code a few things in my templates that used this plugin. Thanks!

**Comment by michaelrog** [comment]
Yes, I'm planning to release a version for Craft 5.x. I'll update this thread when it's out. (In the meantime, if you're feeling industrious, feel free to submit a PR!)

**Comment by TUSAB-web** [comment]
Any chance the above pull request will work?

**Comment by TUSAB-web** [comment]
Just wanted to check on this again since it’s been a couple months without any news...

**Comment by bfjare** [comment]
I would appreciate this as well.

**Comment by michaelrog** [comment]
Thanks for the PR, @tvd0x21 — SuperSort `5.0.0` is out now. 🚀
