### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by brandondeweese** [TopShelfCraft/SuperSort#4]
Hi! I really love this plugin. 

Is there a way to use this with pagination?

{% set grants = craft.entries.section('grants')%}
{% paginate grants.limit(5)  | supersort('sortAs', { something } ) as pageEntries  %} // Order works here. It orders ALL entries. superSort throws an error.
{% for entry in pageEntries %} // If I put supersort here, it'll only sort what's already paginated.

Basically, I need to sort through ALL data then sort it.

**Comment by michaelrog** [comment]
Craft's `{% pagination %}` tag only works on ElementCriteriaModel objects (not on normal arrays). This allows Craft to optimize performance at the query level, to only fetch the elements that are needed for a particular page.

(When you use the `sortAs` method in SuperSort, it requires calculating a derivative property on _all_ the items in an array, which means we have to instantiate _all_ the elements in a set, not just the ones that will appear on a single page. If there are a lot of elements in a set, this could be _very_ slow.)

However, I do understand your use case. Technically, you _could_ use SuperSort in conjunction with `craft.request` params and array slices to achieve your own pagination of SuperSort-ed elements... But probably a better route would be to calculate the derivative sorting value at Element save (using something like a Preparse field), and then use Craft's native pagination, ordered by your pre-cached value.

FWIW, I'm available to provide implementation support for any of the above — support@topshelfcraft.com
