### ISSUE TITLE
Examples in Readme use incorrect syntax

### ISSUE THREAD

**Issue by piotrpog** [TopShelfCraft/SuperSort#7]
Instead this:
`{% upcomingEvents | supersort('sortAs', '{eventDates.first.date}') %}`
It should be this:
`{% set upcomingEvents = upcomingEvents  | supersort('sortAs', '{eventDates.first.date}') %}`
This error occurs also with other examples.

**Comment by michaelrog** [comment]
Thanks for pointing this out, @piotrpog! Would you care to PR a correction?

**Comment by piotrpog** [comment]
Sure, why not :)

**Comment by michaelrog** [comment]
Thank you!
