### ISSUE TITLE
Sort by multiple fields

### ISSUE THREAD

**Issue by kaspar-allenbach** [TopShelfCraft/SuperSort#9]
Is it possible to sort first by `field X `then by `field Y`
Both fields are just text fields

This should be the sort order:

0. `fieldX - fieldY`
1. Abram - Poshk,
2. Andreyev - À propos du concert de la semaine dernière,
3. Andreyev - Bern Trio,
4. Andreyev - Flex I-III,
5. Andreyev - La pendule de profil,
6. Andreyev - Le malheur adoucit les pierres,
7. Andreyev - Locus Solus,
8. Andreyev - Midnight Audition,
9. Andreyev - Moving,
10. Andreyev - Neues Werk,
11. Andreyev - Passages,
12. Andreyev - PLP,
13. Andreyev - Proton-Beschwörung,
14. Andreyev - vérifications,
15. Andriessen - Hoketus,
16. Arias - #YouToo?,
17. Arteaga - Tocapu no. 2,
18. Arter - …Wotan…,
19. Arter - Medusa,
20. Asuroglu - FAÇADE,
21. Avraamov - Sinfonija Gudkow,
22. Azzan - Wasteland_apparent emptiness,

# Sort after related field
I want to first group by a related entry then by the title
```
{% for entry in allEntriesSorted
  | supersort('natcasesortAs', '{{object.komponistRelated | first.nachname}}')
%}
```
Result:
(First string is correct. last string is not. Note how position 3 should be position 2)

1. Abram - Poshk
2. Andreyev - Neues Werk
3. Andreyev - Le malheur adoucit les pierres
4. Andreyev - Moving
5. Andreyev - La pendule de profil
6. Andreyev - vérifications
7. Andreyev - Midnight Audition
8. Andreyev - À propos du concert de la semaine dernière
9. Andreyev - Bern Trio
10. Andreyev - Passages
11. Andreyev - Locus Solus
12. Andreyev - Flex I-III
13. Andreyev - Proton-Beschwörung
14. Andreyev - PLP
15. Andriessen - Hoketus
16. Arias - #YouToo?
17. Arteaga - Tocapu no. 2
18. Arter - …Wotan…
19. Arter - Medusa
20. Asuroglu - FAÇADE
21. Avraamov - Sinfonija Gudkow
22. Azzan - Wasteland_apparent emptiness

# Chaining sort ?
i guess chaining the filters is not a good idea:

```
{% for entry in allEntriesSorted
  | supersort('natcasesortAs', '{{object.komponistRelated | first.nachname}}')
  | supersort('ksort', '{{entry.title}}')
%}
```
1. Andreyev - Neues Werk
2. Arias - #YouToo?
3. Abram - Poshk
4. Asuroglu - FAÇADE
5. Andreyev - Proton-Beschwörung
6. Arter - Medusa
7. Avraamov - Sinfonija Gudkow
8. Arteaga - Tocapu no. 2
9. Azzan - Wasteland_apparent emptiness
10. Andreyev - Flex I-III
11. Andreyev - Locus Solus
12. Andreyev - Passages
13. Andreyev - Le malheur adoucit les pierres
14. Andriessen - Hoketus
15. Arter - …Wotan…
16. Andreyev - Bern Trio
17. Andreyev - À propos du concert de la semaine dernière
18. Andreyev - Midnight Audition
19. Andreyev - vérifications
20. Andreyev - La pendule de profil
21. Andreyev - Moving
22. Andreyev - PLP

This does work but it doesn't sort it alphabeticaly. It looks pretty random 

or like this: 
```
{% for entry in allEntriesSorted 
  | supersort('natcasesortAs', '{{object.komponistRelated | first.nachname}}, title')
%}
```
1. Abram - Poshk
2. Andreyev - Bern Trio
3. Andreyev - Flex I-III
4. Andreyev - La pendule de profil
5. Andreyev - Le malheur adoucit les pierres
6. Andreyev - Locus Solus
7. Andreyev - Midnight Audition
8. Andreyev - Moving
9. Andreyev - Neues Werk
10. Andreyev - Passages
11. Andreyev - PLP
12. Andreyev - Proton-Beschwörung
13. Andreyev - vérifications
14. Andreyev - À propos du concert de la semaine dernière
15. Andriessen - Hoketus
16. Arias - #YouToo?
17. Arteaga - Tocapu no. 2
18. Arter - Medusa
19. Arter - …Wotan…
20. Asuroglu - FAÇADE
21. Avraamov - Sinfonija Gudkow
22. Azzan - Wasteland_apparent emptiness

Is this even possible?

**Comment by kaspar-allenbach** [comment]
this is just geting absudly complex. I need to find another solution

**Comment by michaelrog** [comment]
Check out Craft's [`multisort`](https://docs.craftcms.com/v3/dev/filters.html#multisort) filter for this. 😃
